# TRIPVIEWER
---
# POD
apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-deployment
  namespace: web
  labels:
    app: tripviewer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      # TRIPVIEWER
      - name: tripviewer
        image: registrynom9737.azurecr.io/openhack/tripviewer:1.0
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 150m
            memory: 64Mi
          limits:
            cpu: 250m
            memory: 256Mi
        env:
        - name: TRIPS_API_ENDPOINT
          value: http://trips.api
        - name: USERPROFILE_API_ENDPOINT
          value: http://users-profiles.api
---
# SERVICE
apiVersion: v1
kind: Service
metadata:
  name: tripviewer
  namespace: web
spec:
  type: ClusterIP #ClusterIP
  selector:
    app: tripviewer
  ports:
  - name: tripviewer-http
    protocol: TCP
    port: 80
    targetPort: 80
