# USER-JAVA
---
# POD
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java-deployment
  namespace: api
  labels:
    app: user-java
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      # USER JAVA
      - name: user-java
        image: registrynom9737.azurecr.io/openhack/user-java:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 50m
            memory: 400Mi
          limits:
            cpu: 50m
            memory: 400Mi
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            secretKeyRef:
              name: environment
              key: ASPNETCORE_ENVIRONMENT
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              name: sqlserver
              key: SQL_SERVER
        - name: SQL_DBNAME
          valueFrom:
            secretKeyRef:
              name: sqldbname
              key: SQL_DBNAME
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: sqluser
              key: SQL_USER
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlpassword
              key: SQL_PASSWORD
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-user-msi"
---
# SERVICE
apiVersion: v1
kind: Service
metadata:
  name: user-java
  namespace: api
spec:
  type: ClusterIP #LoadBalancer
  selector:
    app: user-java
  ports:
  - name: user-java-http
    protocol: TCP
    port: 80
    targetPort: 80



