## ROLE BINDINGS
# API DEV
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-dev-web-reader
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-reader
subjects:
- kind: Group
  namespace: api
  name: TO BE DEFINED
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-dev-api-writer
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-writer
subjects:
- kind: Group
  namespace: api
  name: TO BE DEFINED
---
# WEB DEV
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-dev-api-reader
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-reader
subjects:
- kind: Group
  namespace: web
  name: TO BE DEFINED
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-dev-web-writer
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-writer
subjects:
- kind: Group
  namespace: web
  name: TO BE DEFINED