## ROLE BINDINGS
# API DEV
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-dev-web-reader
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-reader
subjects:
- kind: Group
  namespace: api
  name: 91753950-506c-41ee-b1ed-6153af3f3c77
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: api-dev-api-writer
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-writer
subjects:
- kind: Group
  namespace: api
  name: 91753950-506c-41ee-b1ed-6153af3f3c77
---
# WEB DEV
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-dev-api-reader
  namespace: api
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: api-reader
subjects:
- kind: Group
  namespace: web
  name: 2909acbb-1da6-415a-9aad-af3093c3ecec
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: web-dev-web-writer
  namespace: web
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: web-writer
subjects:
- kind: Group
  namespace: web
  name: 2909acbb-1da6-415a-9aad-af3093c3ecec