# POI
apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-deployment
  labels:
    app: poi
spec:
  replicas: 1
  selector:
    matchLabels:
      app: poi
  template:
    metadata:
      labels:
        app: poi
    spec:
      containers:
      # POI
      - name: poi
        image: registrynom9737.azurecr.io/openhack/poi:latest
        ports:
        - containerPort: 80
        resources:
          resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
        envFrom:
        - secretRef:
            name: sql-secrets

---
apiVersion: v1
kind: Service
metadata:
  name: poi
  namespace: api
spec:
  type: ClusterIP #LoadBalancer
  selector:
    name: poi
  ports:
  - name: poi-app-http
    protocol: TCP
    port: 80
    targetPort: 80