# TRIPVIEWER
---
# POD
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips-deployment
  namespace: api
  labels:
    app: trips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      # TRIPS
      - name: trips
        image: registrynom9737.azurecr.io/openhack/trips:1.0
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
        env:
        - name: CREDENTIAL_METHOD
          value: username_and_password
        - name: IDENTITY_CLIENT_ID
          value: ""
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            secretKeyRef:
              name: environment
              key: ASPNETCORE_ENVIRONMENT
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              name: sqlserver
              key: SQL_SERVER
        - name: SQL_DBNAME
          valueFrom:
            secretKeyRef:
              name: sqldbname
              key: SQL_DBNAME
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: sqluser
              key: SQL_USER
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlpassword
              key: SQL_PASSWORD
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-user-msi"
---
# SERVICE
apiVersion: v1
kind: Service
metadata:
  name: trips
  namespace: api
spec:
  type: ClusterIP #LoadBalancer
  selector:
    app: trips
  ports:
  - name: trips-http
    protocol: TCP
    port: 80
    targetPort: 80