# TRIPVIEWER
---
# POD
apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips-deployment
  labels:
    app: trips
spec:
  replicas: 1
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      # USERS
      - name: trips
        image: registrynom9737.azurecr.io/openhack/trips:1.0
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 250m
            memory: 64Mi
          limits:
            cpu: 500m
            memory: 256Mi
        env:
        - name: CREDENTIAL_METHOD
          value: username_and_password
        - name: IDENTITY_CLIENT_ID
          value: ""
        envFrom:
        - secretRef:
            name: sql-secrets
---
# SERVICE
apiVersion: v1
kind: Service
metadata:
  name: trips
spec:
  type: ClusterIP #LoadBalancer
  selector:
    app: trips
  ports:
  - name: trips-http
    protocol: TCP
    port: 80
    targetPort: 80