# USERS-PROFILES
---
# POD
apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-profiles-deployment
  namespace: api
  labels:
    app: users-profiles
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users-profiles
  template:
    metadata:
      labels:
        app: users-profiles
    spec:
      containers:
      # USERS
      - name: users-profiles
        image: registrynom9737.azurecr.io/openhack/userprofile:1.0
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 100m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
        env:
        - name: ASPNETCORE_ENVIRONMENT
          valueFrom:
            secretKeyRef:
              name: environment
              key: ASPNETCORE_ENVIRONMENT
        - name: SQL_SERVER
          valueFrom:
            secretKeyRef:
              name: sqlserver
              key: SQL_SERVER
        - name: SQL_DBNAME
          valueFrom:
            secretKeyRef:
              name: sqldbname
              key: SQL_DBNAME
        - name: SQL_USER
          valueFrom:
            secretKeyRef:
              name: sqluser
              key: SQL_USER
        - name: SQL_PASSWORD
          valueFrom:
            secretKeyRef:
              name: sqlpassword
              key: SQL_PASSWORD
        volumeMounts:
        - name: secrets-store01-inline
          mountPath: "/mnt/secrets-store"
          readOnly: true
      volumes:
        - name: secrets-store01-inline
          csi:
            driver: secrets-store.csi.k8s.io
            readOnly: true
            volumeAttributes:
              secretProviderClass: "azure-kvname-user-msi"
---
# SERVICE
apiVersion: v1
kind: Service
metadata:
  name: users-profiles
  namespace: api
spec:
  type: ClusterIP #LoadBalancer
  selector:
    app: users-profiles
  ports:
  - name: users-profiles-http
    protocol: TCP
    port: 80
    targetPort: 80