# USER-JAVA
---
# POD
apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java-deployment
  namespace: api
  labels:
    app: user-java
spec:
  replicas: 1
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      # USERS
      - name: user-java
        image: registrynom9737.azurecr.io/openhack/user-java:latest
        ports:
        - containerPort: 80
        resources:
          requests:
            cpu: 150m
            memory: 64Mi
          limits:
            cpu: 200m
            memory: 256Mi
        envFrom:
        - secretRef:
            name: sql-secrets
---
# SERVICE
apiVersion: v1
kind: Service
metadata:
  name: user-java
  namespace: api
spec:
  type: ClusterIP #LoadBalancer
  selector:
    app: user-java
  ports:
  - name: user-java-http
    protocol: TCP
    port: 80
    targetPort: 80



